name: Cleanup Workflow Runs

on: [workflow_dispatch]

# REMOVE IF THE TOKEN YOU ARE USING ALREADY HAS THESE PERMISSIONS
permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete Workflow Runs
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
